---
apiVersion: "v1"
kind: "Service"
metadata:
  labels:
    app.kubernetes.io/name: "backend-service"
    app.kubernetes.io/version: "0.0.1-SNAPSHOT"
    cloud.spring.io/enabled: "true"
    cloud.spring.io/register: "true"
  name: "backend-service"
spec:
  ports:
    - name: "http"
      port: 8091
      targetPort: 8091
  selector:
    app.kubernetes.io/name: "backend-service"
    app.kubernetes.io/version: "0.0.1-SNAPSHOT"
  type: "ClusterIP"
---
apiVersion: "apps/v1"
kind: "Deployment"
metadata:
  labels:
    app.kubernetes.io/name: "backend-service"
    app.kubernetes.io/version: "0.0.1-SNAPSHOT"
  name: "backend-service"
spec:
  replicas: 1
  selector:
    matchLabels:
      app.kubernetes.io/name: "backend-service"
      app.kubernetes.io/version: "0.0.1-SNAPSHOT"
  template:
    metadata:
      labels:
        app.kubernetes.io/name: "backend-service"
        app.kubernetes.io/version: "0.0.1-SNAPSHOT"
    spec:
      containers:
        - env:
            - name: "KUBERNETES_NAMESPACE"
              valueFrom:
                fieldRef:
                  fieldPath: "metadata.namespace"
          image: "haybu/backend-service:v1"
          imagePullPolicy: "IfNotPresent"
          livenessProbe:
            failureThreshold: 3
            httpGet:
              path: "/actuator/health"
              port: 8091
              scheme: "HTTP"
            initialDelaySeconds: 0
            periodSeconds: 30
            successThreshold: 1
            timeoutSeconds: 10
          name: "backend-service"
          ports:
            - containerPort: 8091
              name: "http"
              protocol: "TCP"
          readinessProbe:
            failureThreshold: 3
            httpGet:
              path: "/actuator/health"
              port: 8091
              scheme: "HTTP"
            initialDelaySeconds: 0
            periodSeconds: 4
            successThreshold: 1
            timeoutSeconds: 10
